### ISSUE TITLE
include all life cycle methods

### ISSUE THREAD

**Issue by caranicas** [photoshelter/generator-polymer-init-element-scaffold#14]
### Expected Behavior

Generate a template with all lifecycle methods.

### Current Behavior

Only has the constructor and attached methods.

### Possible Solution :bulb:

Add them to them templates...

### Tasks :octopus:
- [x] add them to 1.x
- [x] add them to 2.0
- [x] add them vanilla
