### ISSUE TITLE
Overhaul element demarcation 

### ISSUE THREAD

**Issue by caranicas** [photoshelter/generator-polymer-init-element-scaffold#22]
:wrench: :sparkles:

## Issue

Right now style and behavior are given their own options when really each of them are a type of element you can make within a particular version. 

You can make a 1.X style and a 2.0 behavior but not their counter parts. And you can make neither for vanilla web components. 

### Expected Behavior

You should be able to pick the version of the element you want and then what type of element you want to create.

### Current Behavior

1.x, 2.0, style, behavior, vanilla,  are all top level options. 

### Possible Solution :bulb:

Break out versions into folders. and give each version an sub folder with a template for the specific type of element. `component` `behavior` `style`.

### Tasks :octopus:

- [x] break out all the elements.
- [x] update the variable names.
- [x] update the yeoman process. 
- [x] test test test
