### ISSUE TITLE
Add more example features. 

### ISSUE THREAD

**Issue by caranicas** [photoshelter/generator-polymer-init-element-scaffold#37]
:sparkles: 

### Expected Behavior

The template should demonstrate all the things a polymer component can do. 

### Current Behavior

There is only limited behavior demonstrated by the template. 

### Tasks :octopus:

- [ ] add reflect to attribute
- [ ] complex computed property
- [ ] add observers array
- [ ] add listeners array
- [ ] add a getter

**Comment by Westbrook** [comment]
Are `get` and it's equally awesome opposite `set` really Polymer component contexts the way the other features you've outline herein are?

**Comment by caranicas** [comment]
No, they aren't part of polymer, but since they will more often than not be in a component, I thought that adding it to the template would be a helpful guide, as well as help enforce ordering.
