### ISSUE TITLE
Move building and pages to tasks

### ISSUE THREAD

**Issue by caranicas** [photoshelter/generator-polymer-init-element-scaffold#42]
:wrench:  

### Expected Behavior

`gulpfile.js` should be clear of implementation details and just be the commands that a user will execute.

### Tasks :octopus:

- [ ] create a build task file
- [ ] create a pages task file
- [ ]use them to compose the top level tasks
